import { Tenant } from "interfaces/tenant";

const Tenants: Record<string, Tenant> = {
  "rekeningku": {
    "id": 38,
    "name": "Rekeningku",
    "logo": "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/rekeningku-281d8b7c-dd03-4a10-867f-8dffa4da1833.png",
    "slug": "rekeningku",
    "position": [
      10,
      616
    ],
    "pageType": 0,
    "aboutUs": "Rekeningku merupakan marketplace atau tempat dimana kamu bisa jual atau beli aset kripto seperti bitcoin, ethereum, tron, litecoin, dogecoin, just dan lain sebagainya. Kantor Rekeningku terletak di Equity Tower Lantai 11E, SCBD Lot. 9, Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan Rekeningku juga salah satu exchanger yang mendapat surat izin sebagai pedagang fisik aset kripto yang dirilis oleh BAPPEBTI di bawah KEMENDAG dengan Nomor 0006/BAPPEBTI/CP-AK/03/2020. Saat ini Rekeningku menempati peringkat 63 di coinmarketcap.com/rangkings/exchanges dengan volume transaksi sebesar $9.035.898. Member Rekeningku juga mayoritas adalah muda-mudi yang tertarik menjadikan aset kripto sebagai bentuk investasi. Kamu tertarik? Yuk mulai buat akun di Rekeningku https://www.rekeningku.com/",
    "galleryText": "",
    "hiring": "",
    "socialMedia": {
      "email": "",
      "linkedin": "https://www.linkedin.com/company/rekeningku-com",
      "instagram": "https://www.instagram.com/Rekeningkucom/"
    },
    "videoUrl": "https://youtube.com/embed/5gYI3391HE4",
    "gallery": [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/rekeningku_new/rekeningku.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/rekeningku_new/rekeningku2.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/rekeningku_new/rekeningku3.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/rekeningku_new/rekeningku6.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/rekeningku_new/rekeningku7.jpg"
    ],
    contactLink: "",
  },
  okegarden: {
    id: 39,
    name: "OkeGarden",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-153a66ec-6bbf-4e3d-9b34-f866b9654a35.png",
    slug: "okegarden",
    position: [300, 800],
    pageType: 0,
    aboutUs:
      "OKE Garden adalah layanan jasa desain, pembuatan dan perawatan taman untuk mewujudkan taman yang asri dengan mudah. OKE Garden hadir untuk mengatasi masalah yang ada di industri pertamanan yaitu, ketidakpastian kerja tukang taman, petani tanaman hias dan juga kebingungan pelanggan terkait informasi pembuatan taman terutama mengenai transparansi harga. Layanan jasa OKE Garden berusaha membuat taman sesuai dengan impianmu karena kami percaya #asriitumudah.",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/okegarden/",
      instagram: "https://www.instagram.com/okegarden/\n",
    },
    videoUrl: "https://youtube.com/embed/fR9WpGHjvF4",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-b0b3035c-7161-4b3e-8cee-3d79e3d8e826.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-9f4cca18-869f-4e2a-9edf-f80ee21b14a8.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-2bfaef8d-4427-4a31-816c-480e9ce4342a.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-3db7ae10-7148-494a-b469-066fd16afd3b.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-7c9c7f71-df2a-47d5-bf83-969110a8ff55.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-5dd031d6-cdf7-4629-b4eb-758d855a1e27.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-738fb3d0-8182-4ee0-b585-b0c7b485ed18.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-cf455636-da82-4da6-9b8b-984757d1a3d8.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-6e9543e8-c443-4b7f-a6f0-fe60d0005266.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-d6b3ff94-4e6e-441a-844f-3d52c02d82a5.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/okegarden-b945ade4-b79a-42f1-8e00-9653787b2fed.jpeg",
    ],
    contactLink: "https://wa.me/081382166012",
  },
  desaloka: {
    id: 40,
    name: "Desaloka",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/desaloka-af046188-418a-48d7-8366-079593a3ceeb.png",
    slug: "desaloka",
    position: [184, 230],
    pageType: 0,
    aboutUs:
      "Desaloka Indonesia, memiliki visi untuk memajukan desa - desa di Indonesia demi mewujudkan pemerataan ekonomi. Dengan beberapa layanan yang kami tawarkan, kami memiliki ambisi untuk bisa membantu memajukan desa - desa di Indonesia, seiring dengan misi jangka panjang Indonesia",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "",
      linkedin: "",
      instagram: "https://www.instagram.com/desalokaindonesia/",
    },
    videoUrl: "https://youtube.com/embed/v59BjW18scs",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/desaloka-20e60109-6428-47e2-b189-e75899cddd6a.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/desaloka-7bacd1bd-fe48-4952-ac96-d83bf6c83773.png",
    ],
    contactLink: "https://wa.me/6285707765684",
  },
  studiin: {
    id: 41,
    name: "Studi.in",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/studiin-23b919fc-6ed1-4856-acb2-e7638369194f.png",
    slug: "studiin",
    position: [300, 975],
    pageType: 0,
    aboutUs:
      "Studi.in adalah platform yang mempertemukan pelajar dengan tutor pilihan di waktu dan tempat sesuai dengan kebutuhanmu dengan biaya yang variatif. Tidak hanya itu, disini siapapun memiliki kesempatan untuk menjadi tutor kapan pun dan dimana pun. Untuk informasi lebih lanjut, follow akun Instagram dan LinkedIn kita @studiin.id",
    galleryText: "",
    hiring: "http://bit.ly/StudiinInternship",
    socialMedia: {
      email: "Studiin.id@gmail.com",
      linkedin: "https://www.linkedin.com/company/studi-in/?viewAsMember=true",
      instagram: "\nhttps://www.instagram.com/studiin.id/\n",
    },
    videoUrl: "https://youtube.com/embed/ocl51Vqdsyk",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/studiin-d6419507-085d-45be-a76d-e93880014cd6.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/studiin-c0d61f6e-6567-4769-8f95-5b90aee8278a.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/studiin-7a18f069-a849-405c-9a0b-6089a9510ef8.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/studiin-0628e67e-c6a2-4aaf-a850-6d351e096976.jpeg",
    ],
    contactLink: "wa.me/6287869919423",
  },
  idstar: {
    id: 75,
    name: "IDStar Cipta Teknologi",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idstar-8e9cd203-5b27-4159-95f6-eaa881f9e059.png",
    slug: "idstar",
    position: [150, 380],
    pageType: 0,
    aboutUs:
      "PT IDStar Cipta Teknologi focuses on providing professional IT services through consultation for individuals and companies. We aim to be your one-stop solution, by providing IT consultancy for CRM, RPA, Mobile Apps, HR, and Digital Transformation. \nWe also endeavor to educate young individuals in developing their skills and becoming professionals to meet the current demand in their respective industry in this era of technology through classes, trainings, and events.",
    galleryText: "",
    hiring: "https://www.kalibrr.com/c/pt-idstar-cipta-teknologi/jobs",
    socialMedia: {
      email: " recruitment.ids@idstar.co.id ",
      linkedin: "https://www.linkedin.com/company/pt-idstar-cipta-teknologi",
      instagram: "https://www.instagram.com/idstar.id",
    },
    videoUrl: "https://youtube.com/embed/8BCw_4GYjv0",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idstar-1da0aeb8-2f97-47d3-957f-7937148a81b5.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idstar-9581b8d0-d6c4-420a-9db7-a8b0c1fa372c.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idstar-3de7833d-2f84-437e-8a6e-2b4cfdf7db23.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idstar-74f8208a-9443-499f-ab1b-c73e9026360a.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idstar-e64a5ceb-5450-47d8-8642-097cfb37bb50.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idstar-ce2f4c0f-f53b-4d2f-9581-874ede8fb2f1.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idstar-9db6f23f-c18b-4beb-afcc-790d5ac03e69.jpg",
    ],
    contactLink: "wa.link/mp8dqv",
  },
  "sportigo": {
    "id": 42,
    "name": "Sportigo",
    "logo": "http://nyc3.digitaloceanspaces.com/arkavidia/production/realitfestyep/sportigo-logo-1.png",
    "slug": "sportigo",
    "position": [
      275,
      1050
    ],
    "pageType": 0,
    "aboutUs": "Sportigo is a sport tech company based in Jakarta. We make a platform where individual could join group sport activity like futsal and football as easy as joining fitness class. We make a football performance app using data and statistic based on real life match or training.",
    "galleryText": "",
    "hiring": "https://docs.google.com/forms/d/e/1FAIpQLScqxNkPam_cFtGGkKIwYhC2EgeI767r5dm0RV6UPxe0kKT4DQ/viewform?usp=sf_link",
    "socialMedia": {
      "email": "sportigoindo@gmail.com",
      "linkedin": "https://www.linkedin.com/company/sportigo-indonesia/",
      "instagram": "https://www.instagram.com/sportigofc/ "
    },
    videoUrl: "https://youtube.com/embed/FkkjVjFCfg8",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sportigo-c66ae5ad-fb0e-431e-b873-4047463b633a.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sportigo-08ac5a73-07b2-4947-b227-13550826e4d4.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sportigo-811399ce-28a7-42ad-8e2a-c806eeeb7f51.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sportigo-92d279b7-9484-46a8-99eb-da6feb5e51da.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sportigo-3b2ed9ae-a12f-4c64-999c-f87e7feb682d.jpg",
    ],
    contactLink: "https://wa.me/085771559962",
  },
  createit: {
    id: 43,
    name: "Create It",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/createit-691dd605-e4aa-4eca-9409-71ffa34e15d4.png",
    slug: "createit",
    position: [170, 86],
    pageType: 0,
    aboutUs:
      "Create It is an EduTech Platform focused on Project-Based and Creative Economy-related curriculum to help final year students, fresh grads, and career-shifters to become creative agile talent to build a professional track in the digital & creative industry.  So far, we have 3 major Profession outcomes: Creativepreneur, professional, and Content Creators / Freelance. Let\u2019s Create with Create It",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "contact@createit.id",
      linkedin: "www.linkedin.com/company/createitindonesia",
      instagram: "instagram.com/@createit_id\n",
    },
    videoUrl: "https://youtube.com/embed/P6dmADqgiMQ",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/createit-f05e8020-944e-45ba-9fab-0239a0afe725.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/createit-10aa37c0-c4b6-419c-9ddf-4b8f749608bc.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/createit-2966e876-eb13-4efb-bb14-d08430a8a258.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/createit-98d01625-86fe-43e9-bd43-bd2000b3cfac.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/createit-5e5b7209-86dc-4080-b7c5-41a05acd808b.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/createit-d12274cc-41fe-435a-a58c-263d0ca29743.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/createit-c66ee79d-9149-48b0-aaa9-4dfcb230b4ae.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/createit-7ea020fc-c74d-4e20-aa7c-d912cd8cd9d1.jpeg",
    ],
    contactLink: "https://chat.whatsapp.com/HuOhKTVdq7gJkQ1BIpliUU",
  },
  philoit: {
    id: 44,
    name: "Philoit",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/philoit-3a447689-0158-4f20-a8c8-e2a563ab21c6.png",
    slug: "philoit",
    position: [170, 350],
    pageType: 0,
    aboutUs:
      "Diluncurkan tahun 2019, Philoit adalah platform tanya jawab untuk mencari pengetahuan dan saling berbagi ilmu serta pengalaman dengan pengguna lainnya yang dilengkapi dengan fitur-fitur asik seperti gamifikasi, level, poin, title, dan coin redeem untuk kamu generasi muda millennial Indonesia. Temukan jawaban, jadilah jawaban.",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/philoitid/",
      instagram: "https://www.instagram.com/philoit.id/",
    },
    videoUrl: "",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/philoit-efb7a5aa-4b85-48e9-b0b5-303ffa0fc8d8.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/philoit-380b0b76-33e1-4bd0-b282-276fffd64d79.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/philoit-18e63882-272e-41f1-8dcf-c736f12e600c.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/philoit-dd8ace29-11b1-42c1-92a5-14fa86fcb68e.png",
    ],
    contactLink: "https://chat.whatsapp.com/KHmaHfMtDg3GwWRwAz0FiZ",
  },
  cakap: {
    id: 45,
    name: "Cakap",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/cakap-c0a32b5d-5f38-463a-82aa-a9e9ea8ffe2c.jpg",
    slug: "cakap",
    position: [117, 508],
    pageType: 0,
    aboutUs:
      "Cakap adalah platform yang menyediakan pembelajaran dengan interaksi 2 arah antara pelajar dengan para profesional di Asia Pasifik untuk belajar dan mengembangkan bakat spesifik sesuai dengan kebutuhan kapanpun dan dimanapun. CAKAP menyediakan solusi edukasi dengan kurikulum standar internasional untuk memberikan pengalaman belajar daring terbaik.",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "",
      linkedin: "",
      instagram: "",
    },
    videoUrl: "https://youtube.com/embed/FLDO5Lc4k_U",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/cakap-443c2e02-965f-4e92-a2c8-07a4b64cca01.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/cakap-16b41ba3-e25e-4619-8b67-5f8e220527e2.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/cakap-f852bf36-5a19-4d52-b31c-e0f7e0f24da9.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/cakap-56271cee-f91a-4218-9b11-314d5b7ac942.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/cakap-77a33f2c-d0bc-4b93-8ae9-8f8759814f98.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/cakap-3e612cff-9c00-4462-9a49-2f7e2a14c8f8.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/cakap-c95d614b-88d7-42a3-ae8e-48a591abcb76.jpg",
    ],
    contactLink: "https://chat.whatsapp.com/L5am6LYGSwBL8tQqvnEftC",
  },
  icehouse: {
    sponsor: true,
    additionalChallenge:
      "https://drive.google.com/drive/folders/15o-XT1eLy1kXY8YNb1ekopcAWy-H3h7j?usp=sharing",
    id: 46,
    name: "Icehouse",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/icehouse-ccfbaf4e-9ab6-4495-9c5e-166eeca59745.png",
    slug: "icehouse",
    position: [236, 550],
    pageType: 0,
    aboutUs:
      "Founded in South Jakarta, Ice House is the first Google Certified Developer in South East Asia. We design, build and maintain mobile apps and their backends for most of the leading companies in various industries, like financial services, logistics and transportation, e-commerce, entertainment, loyalty and many more.\n\nWe are proud to be 1 of 25 Google Certified Agencies in the world.\n\nThe team is made up of world-class designers, architects, business analysts, developers and project managers who have collectively shipped products for some of the world\u2019s largest companies and most innovative startups.\n\nOur mission is to empower the greatest minds to create the greatest digital experiences.\nPlease visit our website at https://icehousecorp.com/ and watch the video about our office environment here: https://bit.ly/3aFDub9.",
    galleryText: "",
    hiring: "https://icehousecorp.com/careers/",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/ice-house/",
      instagram: "https://www.instagram.com/lifeaticehouse/",
    },
    videoUrl: "https://youtube.com/embed/-4P0MsnLS3Q",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/icehouse-a217498d-bb9f-4b59-ad9d-fc639851ac73.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/icehouse-d4a114dc-8f64-44cd-80fd-d1cfb88742f6.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/icehouse-834f8e58-a672-40fd-a769-a0f9b22f0a6c.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/icehouse-0b345f61-5cab-436d-b652-05de8b69759a.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/icehouse-85b850f3-5929-430a-a58a-60108bebd2c1.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/icehouse-671ff01f-9076-4d10-b8e9-5d9e092f9a63.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/icehouse-4095b315-0529-4756-bf10-edc503701952.jpeg",
    ],
    contactLink: "https://api.whatsapp.com/send?phone=6285659623487",
  },
  "propertree-id": {
    id: 47,
    name: "Propertree.id",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/propertree-id-b63123a1-8a82-4556-9537-7a3a75186a7a.png",
    slug: "propertree-id",
    position: [3, 545],
    pageType: 0,
    aboutUs:
      "Propertree adalah perusahaan teknologi finansial yang melayani pendanaan proyek properti yang menghubungkan Mitra Developer dengan masyarakat secara digital. Kami melakukan digitalisasi inklusi pada pendanaan properti yang padat modal menjadi ritel yang lebih terjangkau bagi pendana.",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/propertree-id/",
      instagram: "https://www.instagram.com/propertreeid/",
    },
    videoUrl: "https://youtube.com/embed/tE2mPgjnYgE",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/propertree-id-6d8b84fd-d909-4855-ba5a-d8872e64b23c.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/propertree-id-5c3c8373-e5ae-48d1-9f72-7281f58a5f0d.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/propertree-id-204a919d-8537-40f7-9200-7ec6c885c573.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/propertree-id-0f97608a-cdde-4d45-80bc-2551d9d02e03.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/propertree-id-397af81b-938a-4443-9a2f-aba45458330d.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/propertree-id-dd4af584-78d3-4c82-b40b-99d943b1f80a.jpeg",
    ],
    contactLink: "wa.me/6281281708874",
  },
  matagi: {
    id: 48,
    name: "Matagi Informasi Pertiwi",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/matagi-36cf1b8e-728f-4eed-925f-772722cb75c8.png",
    slug: "matagi",
    position: [400, 740],
    pageType: 0,
    aboutUs:
      "We are dreamers, doers, geeks and technology addicts! (also gamers). Combine together,\nwe are a diverse team with big ideas. Each of us is an expert and a problem solver, sweat\nthe details and design the solution into a whole picture. We\u2019ve been trusted by some of the\nbest companies and startups to help them achieve their goals.",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "work@matagi.id",
      linkedin: "https://www.linkedin.com/company/matagi-informasi-pertiwi/",
      instagram: "https://www.instagram.com/matagi.id/\n\n\n",
    },
    videoUrl: "https://youtube.com/embed/AD27PhZJTGs",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/matagi-2925418b-0711-4244-83e4-7fe65957804f.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/matagi-2fbdceed-b712-49b6-a783-46001d3b4a88.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/matagi-71d9756d-84d2-4506-bf50-9d84e92f1c9c.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/matagi-7708667d-25a2-4f43-a8a2-c9f34832f82b.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/matagi-2ed964cd-f42b-4340-97fe-7a0a44225097.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/matagi-1cfb42aa-3e23-41e3-90d9-7cd8d4824812.jpg",
    ],
    contactLink: "https://chat.whatsapp.com/FiX86Ia6TV56V20Coteqw4",
  },
  ocistok: {
    id: 49,
    name: "Ocistok",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/ocistok-dfa64987-3206-4aa0-8419-3e1260b87018.png",
    slug: "ocistok",
    position: [325, 700],
    pageType: 0,
    aboutUs:
      "OCISTOK.com adalah sebuah platform belanja grosir impor dan lokal yang menawarkan produk dengan harga termurah, terlengkap, serta terpercaya. Ocistok.com didesain khusus untuk membantu dan memudahkan para pelaku bisnis online maupun offline di Indonesia untuk mendapatkan barang impor maupun lokal yang dibuat semudah berbelanja melalui Marketplace.",
    galleryText: "",
    hiring: "https://ocistok.com/pages/karir-1",
    socialMedia: {
      email: "info@ocistok.com",
      linkedin:
        "https://www.linkedin.com/company/ocistok-com/?viewAsMember=true",
      instagram: "https://www.instagram.com/ocistok/?hl=id",
    },
    videoUrl: "https://youtube.com/embed/_RUbji0kGbE",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/ocistok-9c8b7cc4-a0c7-4acc-b2fc-b87164f746f1.png",
    ],
    contactLink: "https://chat.whatsapp.com/LKou60GvH77Gnv3t0kwjis",
  },
  xendit: {
    id: 50,
    name: "Xendit",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/xendit-d9395c33-85c4-496a-9679-1081254f6196.png",
    slug: "xendit",
    position: [300, 650],
    pageType: 0,
    aboutUs:
      "Xendit adalah perusahaan teknologi keuangan yang menyediakan solusi pembayaran yang\nmenyederhanakan proses pembayaran untuk bisnis di Indonesia dan Filipina, dari UKM,\nstartup e-commerce hingga perusahaan besar. Sebagai startup Indonesia pertama yang\nberhasil lulus dari inkubator YCombinator yang bergengsi di Silicon Valley, Xendit bertujuan\nuntuk membangun infrastruktur pembayaran Indonesia.\n",
    galleryText: "-",
    hiring:
      "https://xendit.co/careers?utm_source=arkavidia-website&utm_medium=referral&utm_campaign=arkavidia-7.0",
    socialMedia: {
      email: "pr@xendit.co",
      linkedin: "https://www.linkedin.com/company/xendit",
      instagram: "https://instagram.com/xendit",
    },
    videoUrl: "https://youtube.com/embed/f70fA9UFmq8",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/xendit-9bc8e364-ce2e-4acd-8248-8586b82f7885.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/xendit-112861dc-1119-4706-b7ba-a21e5e4b13cf.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/xendit-f9d5b779-4d11-4bc1-b1e4-18b6093ee447.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/xendit-d0c595d1-e952-488f-90e8-632252bb0649.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/xendit-ba4cc145-53d0-41cf-820c-f78ce825943f.jpg",
    ],
    contactLink: "https://chat.whatsapp.com/E1Dhwpj67PP77V516pHrpZ",
  },
  qwork: {
    id: 51,
    name: "Qwork",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/qwork-8a947e70-f796-4c8d-ada9-bbef37923c8e.png",
    slug: "qwork",
    position: [60, 830],
    pageType: 0,
    aboutUs:
      "We Empower talents and businesses to sustainably navigate through the gig economy by matching our community of Giggers(Gig Workers) to dynamic manpower needs of businesses. \nFor Businesses \nTransform your workforce by shifting to on-demand, flexible and skilled giggers! \nFor Giggers \nChart your own path and enrich your career with Qwork! \n",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "astrid@qwork.my",
      linkedin: "https://www.linkedin.com/company/qwork-msia/",
      instagram: "https://www.instagram.com/qwork.my/",
    },
    videoUrl: "https://youtube.com/embed/a6v-7OiyFPc",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/qwork-f92725f5-3667-49e3-a3fc-48d7df2e4606.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/qwork-76510db1-d66c-4ae2-afe4-6920b43db957.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/qwork-a3643c86-3ee1-4340-9f52-a2f772572840.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/qwork-97b20b21-051a-456b-8908-1d8a12facd64.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/qwork-be3605c8-9d7e-4a05-b5c4-6194f4c68ffa.png",
    ],
    contactLink: "https://wa.link/ucybi4",
  },
  flocs: {
    id: 52,
    name: "Flocs",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/flocs-33aa2935-ae86-4ed8-a619-72c5404b54fd.png",
    slug: "flocs",
    position: [250, 600],
    pageType: 0,
    aboutUs:
      "Flocs is an app for social profile sharing as the solution of multiple account, social and physical distancing, many links or URLs shared. Our ultimate vision is to build a platform that makes it safe and secure for you to interact with the world around you.",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/flocs",
      instagram: "https://www.instagram.com/flocs.co/\n ",
    },
    videoUrl: "https://youtube.com/embed/2CjwJxTnClQ",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/flocs-a442cf69-1b81-4d7f-9da9-899fe1cb9f08.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/flocs-f5e22fe3-9b6a-419d-8ff5-0d5c411eec77.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/flocs-fce3c89c-86f4-4dd0-9ec3-ff9957099960.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/flocs-9ff3f907-62b1-40b8-8d35-7bd8b0e7a348.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/flocs-b7bd9ae4-7f53-4e95-b367-09a0918b7e6f.jpg",
    ],
    contactLink: "https://wa.me/08122020648",
  },
  avana: {
    id: 53,
    name: "Avana",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/avana-45faa7e6-e283-4442-8a06-75183314f2ad.png",
    slug: "avana",
    position: [250, 150],
    pageType: 1,
    aboutUs:
      "Lahir dari keinginan untuk membantu para pebisnis untuk mendigitalisasi bisnis mereka secara efisien, AVANA didirikan oleh Luqman Adris (sebagai Co-Founder & CEO) dan Yienyee Soh (sebagai Co-Founder & COO). Luqman Adris, lulusan jurusan Teknik Penerbangan Michigan Ann Arbor yang telah berpengalaman mengelola agensi digital selama lebih dari 6 tahun. Sementara Yienyee Soh merupakan lulusan Psikologi dan pendiri dari agregator bisnis online pertama di Malaysia. Keduanya berasal dari latar belakang yang jauh berbeda, namun mengemban visi misi yang sama.\nPerjalanan mereka jelas tidaklah mudah. Namun hingga kini, AVANA telah berkembang ke tiga negara berbeda (Indonesia, Singapura dan Malaysia) dan telah membantu lebih dari 100.000 brand mendigitalisasi bisnis mereka. Bekerjasama dengan Facebook, Google, Instagram, Whatsapp dan puluhan partner-partner lainnya, AVANA terus berinovasi untuk mengembangkan produk terbaik yang dapat memenuhi kebutuhan para pebisnis di masa kini.\n",
    galleryText: "Kantor Jakarta dan Bandung",
    hiring: "https://linktr.ee/ITFestxAvana",
    socialMedia: {
      email: "support@avana.id",
      linkedin: "",
      instagram: "https://www.instagram.com/avana.id/",
    },
    videoUrl: "https://youtube.com/embed/KXV7lhk7OEc",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/avana-2e1c901f-7811-46d3-abb3-e5137c13c07c.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/avana-958b5db6-a5dc-4745-b8b0-1ee974647c3e.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/avana-a45515e8-1e78-44bb-826a-ba64164e25d7.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/avana-7d612e1d-aa06-4941-9f4e-85f5aa2d069c.jpeg",
    ],
    contactLink: "https://wa.me/082210000365",
  },
  agate: {
    id: 54,
    name: "Agate",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/agate-db981bf5-5996-4feb-835e-938b017e6e13.png",
    slug: "agate",
    position: [151, 303],
    pageType: 0,
    aboutUs:
      "Agate is an award-winning game development company headquartered in Bandung, Indonesia. We focus on bringing meaningful play for everyone, everywhere, every day through free-to-play mobile games, premium consumer games, and gamification solutions. Now Agate has grown into the largest Indonesian game development company with more than 200 crews in Bandung and Jakarta. We believe the world will be better when there's joy in it and we believe the game is one way to achieve that.",
    galleryText: "",
    hiring: "https://agate.id/careers/",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/agate-studio/",
      instagram: "https://www.instagram.com/agateint/",
    },
    videoUrl: "https://youtube.com/embed/6xVPko-BgAc",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/agate-634eaac5-3541-4dd6-a102-8a437a528938.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/agate-4fd17c43-ae3b-41fe-b266-0f13d6455967.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/agate-5799f879-8d55-41fd-9c79-6e515cc70f8d.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/agate-436963cd-3d0a-4c4d-91d8-8cf89add0bd2.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/agate-8082536b-f70f-4990-bfb7-8bb191f242e5.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/agate-20d5bcf4-9cf4-4315-8810-effa37b9a888.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/agate-e0b426e7-d724-4776-b20e-f516bc6edf04.png",
    ],
    contactLink: "https://wa.me/6282119923915",
  },
  lindungihutan: {
    id: 55,
    name: "LindungiHutan",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/lindungihutan-c41a8a35-1177-4aab-90b3-f55a1ceb272f.png",
    slug: "lindungihutan",
    position: [150, 650],
    pageType: 0,
    aboutUs:
      "LindungiHutan merupakan platform crowdsourcing online untuk konservasi hutan & lingkungan Indonesia. Melalui LindungiHutan, Anda dapat berdonasi, membuat campaign, menjadi relawan, magang, dan ikut kegiatan seru lainnya. LindungiHutan memiliki berbagai proyek menarik dan berdampak seperti SatuHutan, HutanMerdeka, RawatBumi, KadoBumi, CollaboraTree, dan LivePlanting. Kunjungi situs web lindungihutan.com untuk informasi lengkapnya. Mari #BersamaMenghijaukanIndonesia!",
    galleryText: "",
    hiring: "biolinky.co/lindungihutan",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/lindungihutan/",
      instagram: "https://www.instagram.com/lindungihutan/\n",
    },
    videoUrl: "https://youtube.com/embed/b0LOLIdmsyk",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/lindungihutan-9f27c9d7-8140-4db9-8ed5-b0dc63c1a010.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/lindungihutan-459327b4-fbbe-4b43-a28d-d0e0271b71af.jpeg",
    ],
    contactLink: "wa.me/6281329182514",
  },
  indobot: {
    id: 56,
    name: "Indobot",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/indobot-3d76a200-0d18-4954-b981-fd5856ae3bbd.png",
    slug: "indobot",
    position: [400, 610],
    pageType: 0,
    aboutUs:
      "Indobot Academy merupakan sebuah platform pembelajaran yang mengajarkan cara membuat alat elektronika tepat guna tanpa harus memiliki basic elektronika. Lebih dari sepuluh ribu user sudah belajar elektronika menggunakan kurikulum Indobot serta video pembelajaran step by step dan interaktif. Yuk daftar sekarang dan bergabung bersama komunitas electronics maker Indobot Academy.",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "support@indobot.co.id",
      linkedin: "https://www.linkedin.com/company/indobotacademy/",
      instagram: "https://www.instagram.com/indobot.co.id/",
    },
    videoUrl: "https://youtube.com/embed/xWmczmdECCI",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/indobot-03d3bdbc-2036-4c9b-bb78-78b1c3062080.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/indobot-0ef441fb-75b1-48ca-bb07-d1b715035e10.jpeg",
    ],
    contactLink: "https://wa.me/085731636408",
  },
  kulina: {
    id: 57,
    name: "Kulina",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/kulina-fec49dcd-6d3a-4369-b587-38b55b99d0d4.png",
    slug: "kulina",
    position: [350, 180],
    pageType: 0,
    aboutUs:
      "Kulina is a meal curation platform & delivery service using technology to optimize food supply and logistics, making quality meals affordable for millions of people. Kulina is on the mission of serving the best meal with an outstanding customer experience. Our startup started in 2015 with the aim of eliminating all the unnecessary costs, inefficiencies in food production, and supply chain. Our team currently works on end-to-end food service from designing each day's menu to delivering it to customers' desks.",
    galleryText: "",
    hiring: "https://www.mkt.kulina.id/karir",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/kulina/ ",
      instagram: " https://instagram.com/kulina.id/ \n",
    },
    videoUrl: "https://youtube.com/embed/74B9GL1uBBk",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/kulina-fdbedf16-7c0d-4090-bd8a-4049c29f90fa.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/kulina-8d577e51-0890-4e10-a481-be40bbe4ad8b.jpeg",
    ],
    contactLink: "wa.me/628175484146",
  },
  amartha: {
    id: 58,
    name: "Amartha",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/amartha-2da9b3d1-8ed6-4863-8a0f-28b0015c4e0d.png",
    slug: "amartha",
    position: [380, 450],
    pageType: 0,
    aboutUs:
      "Amartha is pioneering P2P lending for micro entrepreneurs. We connect aspiring unbanked micro-entrepreneurs with lenders interested in making profitable, impactful investments. We have developed our proprietary technology platform and self-learning algorithm to support our marketplace. Our proprietary technology automates key aspects of our operations, including the borrower application process, data gathering, credit decisioning and scoring, and servicing.",
    galleryText: "",
    hiring: "https://careers.amartha.com/",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/amartha/",
      instagram: "https://www.instagram.com/amarthaid",
    },
    videoUrl: "https://youtube.com/embed/8fDhE1k2RtA",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/amartha-44d1a33a-078c-4e24-be2c-6f7256041a89.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/amartha-ed2f0cbf-0188-4099-a0f1-7b958dd04f6c.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/amartha-d4975536-c521-4263-abde-4433d61ece65.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/amartha-ed6005d5-1a24-494a-af7a-d47eedc2dc3c.jpg",
    ],
    contactLink: "wa.me/628119199065",
  },
  latihid: {
    isApplyRegister: true,
    id: 59,
    name: "Latih ID",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/latihid-5932b208-434c-4472-b639-13a5bab0b895.png",
    slug: "latihid",
    position: [210, 990],
    pageType: 0,
    aboutUs:
      "LatihID adalah sebuah platform pembelajaran online yang bertujuan untuk meningkatkan kompetensi dan keahlian UMKM di seluruh Indonesia melalui penyediaan modul pelatihan yang berkualitas dengan biaya yang ekonomis.\nVisi LatihID adalah membantu UMKM agar dapat bersaing di pasar lokal dan pasar internasional, sehingga UMKM dapat berkontribusi dalam meningkatkan perekonomian Indonesia.\n",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "info@latihid.com",
      linkedin: "",
      instagram: "https://www.instagram.com/latihidofficial/\n\n",
    },
    videoUrl: "https://youtube.com/embed/-5_nWWSHBxQ",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/latihid-00682e59-379d-40fc-af1f-e367ed8d2dff.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/latihid-e9066095-163f-4a23-bb9e-18d63962a817.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/latihid-30a48455-755c-4de7-8171-546638f200b7.jpg",
    ],
    contactLink: "https://wa.me/081337488385",
  },
  qlue: {
    id: 60,
    name: "Qlue",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/qlue-9a45c15c-bb04-4c6c-a494-3d0c2c5636de.png",
    slug: "qlue",
    position: [246, 750],
    pageType: 0,
    aboutUs:
      "Established in 2016, Qlue has transformed from a tech startup to a comprehensive smart city provider company in Indonesia. Driven by the mission to accelerate positive changes worldwide, we have built a platform which consists of cutting-edge technology products leveraging workforce management, artificial intelligence (AI) and internet of things (IoT). Three years working on the industry, Qlue received multiple awards, including Global Smart City Contest winner by World Smart City Organization in London (2018), Best M-Government Service Award from the World Government Summit in Dubai (2019), and Startup of the Year from Jumpstart Magazine, Hong Kong (2019).",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/qluesmartcity/",
      instagram: " https://www.instagram.com/qluesmartcity/",
    },
    videoUrl: "https://youtube.com/embed/q8czKikkCZA",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/qlue-gallery/DSC01191.JPG",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/qlue-gallery/DSC02183.JPG",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/qlue-gallery/IMG_5858.JPG",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/qlue-gallery/IMG_5790.JPG",
    ],
    contactLink: "https://wa.me/087883731997",
  },
  "credibook": {
    "sponsor": true,
    "id": 61,
    "name": "Credibook",
    "logo": "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/logo-credibook.png",
    "slug": "credibook",
    "position": [
      450,
      554
    ],
    "pageType": 0,
    "aboutUs": "Aplikasi pencatatan keuangan untuk UMKM",
    "galleryText": "",
    "hiring": "https://forms.gle/CGac1hZ6PscX6yHk8",
    "socialMedia": {
      "email": "contact@credibook.com",
      "linkedin": "https://www.linkedin.com/company/credibook",
      "instagram": "https://www.instagram.com/credibook/"
    },
    videoUrl: "https://www.youtube.com/embed/KdNPnfeuFnk",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/credibook-e9764046-26d0-4d91-9d3a-21d3534c75cd.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/credibook-02f1f278-d3cd-480f-9b43-c8226088ea18.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/credibook-595103e2-6b34-400a-ac03-53ddd6f3d529.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/credibook-5833b90f-7642-4e23-81f6-30faf6c6acbc.jpg",
    ],
    contactLink: "https://wa.me/6287881095392",
  },
  idsindonesia: {
    id: 62,
    name: "IDS Indonesia",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idsindonesia-c4da4df1-834c-45e4-97ef-54557b56905b.png",
    slug: "idsindonesia",
    position: [100, 300],
    pageType: 0,
    aboutUs:
      "PT. IDS Teknologi Indonesia atau dikenal dengan IDS Indonesia, adalah information technology and digital services yang berdiri sejak 2013. Pada awalnya IDS Indonesia hanya focus di dalam implementasi SAP Business One sebuah software Enterprise Resource Planning (ERP) . Dengan berjalannya waktu kami mulai masuk ke custom software development (web , desktop and mobile application) yang kemudian kini bertransformasi menjadi System Integrator (SI).\nBusiness IDS Indonesia per 2020 :\n\u2022 Enterprises Resource Planning (ERP) Business\n\u2022 Business & Data Intelligence Business\n\u2022 Consulting (Digital Transformation & Business Process Consulting) Business\n\u2022 Cloud & Digital Solution Business\n\nCustomer dari IDS cukup bervariasi dari sehi industri mulai dari Biznet Data Center & Biznet Cloud Cloud (Cloud & Telco), Ebiz (IT Services), Haus! (Food and Beverage), Angkasa Pura 2 & Kertajati (Airport Company) hingga ke manufacturing industry seperti Hino Motors, dll.\n\nDengan perkembangan teknologi informasi dan digital yang sangat agile, di masa\nmendatang IDS Indonesia akan masuk ke arena Artificial Inteligence (AI) , Machine\nLearning & Data Science.",
    galleryText: "",
    hiring: "https://ids.co.id/career/",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/idsindonesia/",
      instagram: "https://www.instagram.com/idsindonesia/\n",
    },
    videoUrl: "https://www.youtube.com/embed/D46-JF8qDjo",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idsindonesia-20956b13-824c-49cb-a445-fa36d6be4130.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idsindonesia-169de97c-5b26-479c-bd52-a2059f96e9ff.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idsindonesia-334de4d4-e5c3-4d62-9fce-eb536be12397.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idsindonesia-ca00ebe1-f580-4eaf-aca9-7844f8834019.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idsindonesia-d89c8ded-024e-4912-b2e9-65f00e62501b.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idsindonesia-4cc4a322-1071-4a76-a015-69e2bd1f2f39.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/idsindonesia-a62c11fa-50cd-4494-8f7d-55dcb4a8b480.jpeg",
    ],
    contactLink: "https://wa.me/6281366655594",
  },
  "jooalan": {
    "sponsor": true,
    "id": 79,
    "name": "Jooalan",
    "logo": "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/logo-jooalan.png",
    "slug": "jooalan",
    "position": [
      400,
      680
    ],
    "pageType": 0,
    "aboutUs": "Kelola pesanan online lebih mudah dengan Jooalan!",
    "galleryText": "",
    "hiring": "https://forms.gle/CGac1hZ6PscX6yHk8",
    "socialMedia": {
      "email": "contact@credibook.com",
      "linkedin": "https://www.linkedin.com/company/31340349/",
      "instagram": "https://www.instagram.com/jooalan.id/"
    },
    videoUrl: "https://www.youtube.com/embed/PGDw6gIgcrU",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jooalan-29b1666f-f3d0-4387-acef-a48fc27e3121.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jooalan-2a6ab7f2-684d-4ac4-810e-78b60ab19112.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jooalan-1ffd01ec-af41-401b-bc5c-30963ee44ce5.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jooalan-b77ad006-2ea4-44e0-a88c-f2c7e0c4cf31.png",
    ],
    contactLink: "https://wa.me/6287881095392",
  },
  "tutee-id": {
    id: 64,
    name: "Tutee.id",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/tutee-id-93658fea-ca41-40e2-82b5-2369f33cf83e.png",
    slug: "tutee-id",
    position: [120, 950],
    pageType: 0,
    aboutUs:
      "Tutee.id is a friendly peer-study-group platform with a verified peer tutor that helps college students achieve higher academic performance. We aim to help students find credible tutors easily while giving them access to be one as well, so they can develop themselves by being a tutee or a tutor.\n\nOur initiative started off in January 2020, currently we have accumulated 300+ tutors as our program partners. For the time being, our services are available at 40+ universities in Indonesia.\n\nOur platform provides you the convenience of small study groups with tutors who are active students or young alumni of your university. Our Tutor will gladly help you to prepare for your exam, assignments, or projects. To book classes at Tutee.id, you just need to enter your university and faculty then you can choose a date and time that suits your availability on our website www.tutee.id.",
    galleryText: "",
    hiring: "-",
    socialMedia: {
      email: "tutee.id@gmail.com",
      linkedin: "https://www.linkedin.com/company/tutee-id",
      instagram: "https://www.instagram.com/tutee.id/",
    },
    videoUrl: "https://youtube.com/embed/DZk8Yf_Mdkg",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/tutee-id-5d35f5f0-6dc0-4728-b175-245ce477f8b1.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/tutee-id-41b1aa0a-a7d8-4d80-a604-f252a67dbe68.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/tutee-id-6e39c607-bf1f-4a42-8d39-a4af53e74ce2.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/tutee-id-2aef7a8a-a178-42d8-b84c-f6423634b343.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/tutee-id-0f089e1c-a3c3-4d98-a90f-936bdcfaac17.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/tutee-id-37339265-226a-4aaf-a185-d2542fd07d36.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/tutee-id-71c4b465-5ab9-4921-80cf-7bf7b1b91012.png",
    ],
    contactLink: "https://wa.me/087770303540",
  },
  "automate-all": {
    id: 65,
    name: "Automate All",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/automate-all-6408b0ff-f8bf-4d04-b0dc-683b224b228b.png",
    slug: "automate-all",
    position: [200, 700],
    pageType: 0,
    aboutUs:
      "Automate All adalah startup teknologi yang menyediakan layanan jasa automasi pada proses bisnis di perusahaan. \nDengan visi Menjadi nomer satu dalam membantu perusahaan go automate pada setiap proses bisnisnya ",
    galleryText: "",
    hiring: "-",
    socialMedia: {
      email: "contact@automateall.id",
      linkedin: "https://www.linkedin.com/company/automateall",
      instagram: "https://instagram.com/automateall?igshid=5rtxoz26yziz",
    },
    videoUrl: "https://youtube.com/embed/s2rFq2IWQPE\n",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/automate-all-1343c902-655f-408b-b6af-16395df01520.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/automate-all-b44e8454-f006-4c8c-9deb-9ed63308c7fa.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/automate-all-b4ccf579-c2af-4344-bea7-b0174f7dfcc5.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/automate-all-39877b97-5bce-4b12-8bef-20c6bee4bd59.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/automate-all-f39b3a04-b89f-4ce1-a71c-c4234c5827bd.jpg",
    ],
    contactLink: "http://wa.me/628999211425",
  },
  uangteman: {
    id: 66,
    name: "UangTeman",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/uangteman-494d1404-533f-4903-88c4-3b4715590193.png",
    slug: "uangteman",
    position: [340, 530],
    pageType: 0,
    aboutUs:
      "UangTeman adalah platform pinjaman online di Indonesia milik PT Digital Alpha Indonesia, anak perusahaan dari Digital Alpha Group Pte Ltd. Dengan algoritma berbasis data, UangTeman menyediakan pinjaman mikro jangka pendek yang transparan untuk konsumen dan UMKM. UangTeman telah terdaftar dan diawasi oleh Otoritas Jasa Keuangan (OJK) sebagai layanan pinjaman peer-to-peer online, sesuai dengan Peraturan OJK 77/2016. Untuk informasi lebih lanjut, kunjungi situs www.uangteman.com.",
    galleryText: "",
    hiring: "-",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/4853323/admin/",
      instagram: "https://www.instagram.com/uangteman/?hl=en",
    },
    videoUrl: "https://youtube.com/embed/VmPLWYTr8Hc",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/uangteman-bff5f3f3-845e-40cf-9a12-7c2e5bdf8299.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/uangteman-bf07e9c4-96aa-45a9-b683-4a9d42413dd9.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/uangteman-0722c5e6-d95f-4928-a4bc-ef121fecd6f5.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/uangteman-e2c52fa9-750e-49d4-b25b-046f9c71bc48.jpg",
    ],
    contactLink: "",
  },
  doku: {
    id: 67,
    name: "Doku",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/doku-574db310-2b1b-4406-8a3f-1d3def988a45.png",
    slug: "doku",
    position: [120, 100],
    pageType: 0,
    aboutUs:
      "Transaksi adalah nafas dari perekonomian. Karenanya langkah awal kami dimulai dari sebuah mimpi besar untuk merintis jalan menuju kebebasan bertransaksi. Sebagai pelopor pembayaran elektronik di Indonesia, inovasi teknologi terus dilakukan untuk menghasilkan solusi pembayaran yang bisa menjawab berbagai kebutuhan bisnis, seiring dengan dinamika ekonomi.\n\nSemua mungkin dilakukan bersama DOKU. Mulai dari soal membayar dan menerima pembayaran, hingga transfer dana. Selama lebih dari satu dekade, kami telah bertumbuh bersama dengan perusahaan besar menengah maupun bisnis individu dari berbagai latar belakang. Mulai dari bisnis transportasi, pariwisata, asuransi, retail, donasi, komunitas, peer to peer lending, dan masih banyak lagi. Kolaborasi dengan mitra seperti bank lokal dan internasional, termasuk institusi non-perbankan, telah memperkuat reputasi kami sebagai solusi pembayaran elektronik lokal yang tepercaya. Bersama kami, ekonomi digital di Indonesia akan lebih berenergi.\n\nKini kita makin leluasa untuk bernafas dan bergerak menembus batasan dalam bertransaksi, beragam pilihan sistem pembayaran, hingga menantang waktu dengan sistem transaksi yang real-time.\n\nTransformasi pembayaran, dari konvensional dan menjadi digital, membebaskan kita dari banyak kendala sehingga menghasilkan akses yang lebih cepat menuju literasi keuangan di Indonesia.",
    galleryText: "",
    hiring: "https://doku.forms-db.com/view.php?id=10857\n",
    socialMedia: {
      email: "careertech@doku.com",
      linkedin: "https://www.linkedin.com/company/doku-indonesia/mycompany/",
      instagram: "",
    },
    videoUrl: "https://youtube.com/embed/Chk0Jnu1kJc",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/doku-a4ab176d-32a4-49f9-b1cd-32032906dc1c.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/doku-e8513b52-0403-4dc2-8dc7-d7114d78c4ab.png",
    ],
    contactLink: "https://wa.me/085295845907",
  },
  merempah: {
    id: 68,
    name: "Merempah",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/merempah-b9bbfe24-33b4-4595-a253-37a46070d5cf.png",
    slug: "merempah",
    position: [150, 260],
    pageType: 0,
    aboutUs:
      "Merempah merupakan platform Sistem Informasi berbasis teknologi penyedia rempah-rempah dengan moto \u201cEmpowering, Simple, and Trusted\u201d.\n\nMemiliki visi \n\u201cMenumbuhkan kebanggaan akan kekayaan rempah bagi daerah penghasil dalam upaya pelestarian dan pengembangan rempah sebagai mother spices Indonesia melalui teknologi digital\u201d \n\nMerempah akan hadir untuk membantu proses kegiatan usaha jual-beli rempah, mulai dari transaksi jual-beli hingga pendistribusian sampai ke tangan konsumen. Platform Merempah dapat memberikan layanan meliputi marketing, logistik, distribusi, accounting dan lain sebagainya sesuai dengan kebutuhan kegiatan usaha yang bersangkutan. Menyediakan rempah maupun olahan rempah untuk memenuhi kebutuhan dapur sehari-hari. \n\nSecara spesifik, Merempah ingin membantu proses kegiatan usaha jual-beli rempah yang semula memiliki mata rantai pasok yang panjang dari petani hingga ke tangan konsumen. Mata rantai ini dapat berupa dimulai dari petani rempah yang mayoritas berada di pedesaan, dikumpulkan oleh tengkulak/pengepul kemudian masuk ke pasar mikro melalui Pedagang Pengecer, dan dipasarkan kembali ke pasar makro hingga kemudian sampai pada tangan konsumen.  \n",
    galleryText: "",
    hiring: "https://www.instagram.com/p/CK5Uhv_g6Ew/?igshid=17pikqy2s1v4h",
    socialMedia: {
      email: "merempah@gmail.com",
      linkedin: "https://www.linkedin.com/company/merempah/",
      instagram: "https://www.instagram.com/merempah.id/",
    },
    videoUrl: "https://youtube.com/embed/dZzv-y58PHg",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/merempah-dc12bd3d-94e0-4a8f-892c-f746f845a494.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/merempah-a4a193c2-d7b7-4a29-9b74-1167eacce37a.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/merempah-dc40b469-e5a4-48c1-b931-e7bca7b69c05.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/merempah-af3d9f97-a99c-43b0-86fe-7b0931acd155.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/merempah-66ae7333-e4fc-4053-9814-a45b6ec6386a.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/merempah-d80b701e-d3c7-4060-807a-096e2a5b8fb3.jpeg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/merempah-555b2832-7790-4bc9-b27d-f08da6900771.jpeg",
    ],
    contactLink: "https://wa.me/085226017099",
  },
  "jagel-id": {
    id: 69,
    name: "Jagel.id",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagelid-9fa8936c-e3aa-46ad-942a-89ce492dfa4b.png",
    slug: "jagel-id",
    position: [100, 400],
    pageType: 0,
    aboutUs:
      "Jagel.id adalah aplikasi mobile Android yang dapat membuat aplikasi Android sendiri bagi para penggunanya untuk mengembangkan usaha seperti aplikasi online shop hingga ojek online, dengan cara yang relatif mudah, cepat, tanpa coding, dan biaya terjangkau.",
    galleryText: "",
    hiring: "https://njv92.app.goo.gl/vHtR",
    socialMedia: {
      email: "cs@jagel.id",
      linkedin: "",
      instagram: "https://www.instagram.com/Jagel.id/",
    },
    videoUrl: "https://youtube.com/embed/zN0yFbkDVGA",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-997a1c11-202e-4c48-be18-87f1fbb86cec.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-87d43077-9d1c-409a-b20e-1ca5a07d0f20.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-55ede613-d0d3-46d3-ba98-2850106bedb4.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-eaf75db6-1e82-4f67-8a7e-29c86da9a1a5.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-99c37227-34c9-46bc-a3db-10e0e8277a75.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-cf5a328b-045e-4b65-a4a1-137da4a7d437.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-c1503609-b95d-4c72-a09c-5d8bee789e82.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-eb1618a8-b599-4c40-a804-c7e48902b461.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-f0aa3cc4-2f5c-4015-9ea6-a05623aac24b.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-5e9df56c-8f21-4686-9bfc-7246d6cae943.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-00c857cc-8bd4-4d5a-a3b8-164615532c2e.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-c4ab18d8-2769-41e1-a823-f65d12b41620.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/jagel-id-1105715d-4c00-409e-9bf7-bfcca1a85c61.jpg",
    ],
    contactLink: "https://wa.me/089516320900 ",
  },
  kotakode: {
    id: 70,
    name: "Kotakode",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/kotakode-0aefb480-13f3-4c7b-8f58-7a4576f5b85e.png",
    slug: "kotakode",
    position: [127, 215],
    pageType: 0,
    aboutUs:
      "Kotakode adalah sebuah web platform untuk programmer di Indonesia. Di Kotakode, kamu bisa mendapatkan jawaban atas masalah coding kamu, menulis blog, dan dalam waktu dekat, kamu juga bisa mendapatkan lowongan kerja.\n\nKotakode mempunyai misi untuk menghubungkan dan meningkatkan kualitas programmer Indonesia. Jadi, tunggu apa lagi? Bergabunglah dengan Kotakode sekarang!\n",
    galleryText: "",
    hiring: "https://forms.gle/a4spgnvc38Nqt9cDA",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/kotakode/",
      instagram: "https://www.instagram.com/kotakode/ \n",
    },
    videoUrl: "https://youtube.com/embed/1-hjv8QF-cA",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/kotakode-6e014fac-da16-4e63-9a27-d5ebcb1f9eac.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/kotakode-a8e4c013-6769-44aa-a1d3-57ecf20b04e6.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/kotakode-2110095b-ca29-4be2-8ad7-a6ff3af96e97.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/kotakode-3de75136-9c47-4300-ab3f-c5e6218ff9f3.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/kotakode-5ebedf6c-c2bb-48e1-8e81-5cc8976e0ac5.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/kotakode-6c8c600c-229c-42ef-9c1b-1d64f8543ecb.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/kotakode-d22e1bfb-e66f-4bb6-8a4c-d7a59737a73e.png",
    ],
    contactLink: "",
  },
  hangry: {
    id: 71,
    name: "Hangry",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/hangry-09cfbeb8-a961-4098-8a79-cf7d6cfe8324.png",
    slug: "hangry",
    position: [160, 524],
    pageType: 0,
    aboutUs:
      "Hangry is the first multi-brand virtual restaurant in Indonesia. Founded in September 2019, Hangry\u2019s in-house brands are Moon Chicken, San Gyu, Dari Pada, Nasi Ayam Bude Sari and Ayam Koplo.\n\nToday, Hangry grows by 15 times within one year operating, runs more than 40 outlets in Jabodetabek & Bandung and adds dine-in experience to its service.\n\nHangry is here to make people's moments delightful by providing the best quality food and beverage products with reasonable prices that people can enjoy anytime, anywhere through various online channels.",
    galleryText: "",
    hiring: "https://www.techinasia.com/companies/hangry",
    socialMedia: {
      email: "",
      linkedin: " https://www.linkedin.com/company/wearehangry/",
      instagram: "https://www.instagram.com/hangryindonesia/?hl=en",
    },
    videoUrl: "https://youtube.com/embed/YkS2aaqsXVU",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/hangry-0fcc913a-6ea4-4432-8ce7-4711821fd48a.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/hangry-27e4012c-0f92-4b82-bf90-ca41432e5735.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/hangry-7510c72a-bfd5-4cdb-a634-3ea0b17bb94f.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/hangry-83ccf641-b664-4045-b0a3-d84804af04bd.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/hangry-393ea060-941e-4d76-bc28-f6a785e7aeb0.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/hangry-28826518-b4c6-494c-804f-6d24e56e4d1a.jpg",
    ],
    contactLink: "",
  },
  feedloop: {
    id: 72,
    name: "Feedloop",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/feedloop-ac21b9a6-650f-41f5-bba7-63012b6d7c56.png",
    slug: "feedloop",
    position: [220, 375],
    pageType: 0,
    aboutUs:
      "Feedloop is a technology information and digital product company that can help businesses digitalize and grow their business through a modern platform-based solution. We aim to enhance company's productivity by providing a platform with means to digitalize, analize, and automate the whole process of their business and to enhance customer lifetime value.",
    galleryText: "",
    hiring: "",
    socialMedia: {
      email: "contact@feedloop.io",
      linkedin: "https://www.linkedin.com/company/feedloopio/",
      instagram: "https://www.instagram.com/feedloop.io/",
    },
    videoUrl: "https://youtube.com/embed/zDn4rXfEPJg",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/feedloop-02e11b56-4378-4ad1-aba1-cd6a621771dd.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/feedloop-f0f2cc82-734c-4de7-ba3d-78a325d3b624.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/feedloop-857bcb64-42f5-402c-8b16-d33d10753fe2.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/feedloop-41434c62-2c71-4992-9ac7-b4303e92be62.png",
    ],
    contactLink: "https://wa.me/081324440339",
  },
  codex: {
    sponsor: true,
    id: 73,
    name: "Codex",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/codex-0547cced-80bc-4638-9078-2df281180492.png",
    slug: "codex",
    position: [50, 470],
    pageType: 0,
    aboutUs:
      "CODEX adalah tim yang melakukan rekrutmen khusus untuk support Telkom DXB (Digital and Next Business) Department dalam rangka mengubah Telkom Indonesia dari Perusahaan Telco menjadi Perusahaan Telco Digital. \n\nCODEX is an official recruiter to support Telkom DXB (Digital and Next Business) Department in order to change Telkom Indonesia from Telco Company to Digital Telco Company.",
    galleryText: "",
    hiring: "https://codex.works/",
    socialMedia: {
      email: "",
      linkedin: "https://www.linkedin.com/company/codex-telkom/",
      instagram: "https://www.instagram.com/codex.telkom/",
    },
    videoUrl: "https://youtube.com/embed/0_sue5dx9-Y",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/codex-29d3cbe3-a598-4b81-97a9-fd6facca59ce.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/codex-c0760211-0f02-441a-bd18-214f6c0c00ed.png",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/codex-1781edcf-e3aa-4238-bc94-39f762c95a6b.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/codex-0d25f5bf-2257-4441-a3db-cea64a25678d.jpg",
    ],
    contactLink: "https://wa.me/081218884863",
  },
  sonar: {
    id: 74,
    name: "Sonar",
    logo:
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sonar-4e905c59-40d9-4b41-991c-a8b1fa6ae1d0.png",
    slug: "sonar",
    position: [189, 594],
    pageType: 0,
    aboutUs:
      "Sonar Platform adalah platform yang menempatkan pengguna dalam mempelajari metrik dan menarik kesimpulan berbasis data secara langsung. Sonar menganalisa dan mendengarkan seperti apa suatu brand atau perusahaan di dunia sosial media. Sebagai salah satu Negara pengguna media sosial terbesar di dunia. Indonesia sudah seperti kanvas bagi Sonar. Menganalisis sejumlah percakapan dari berbagai macam bahasa, industri, dan sumber platform yang berbeda.\nDari kanvas inilah Sonar membangun layaknya perpustakaan bahasa yang luas terdiri dari 3 juta artikel dan puluhan terabyte percakapan yang memperkuat basis data analisis sentimen dab terus tumbuh setiap hari. Kunci sukses sebuah percakapan adalah memahami siapa yang anda ajak bicara dan apa yang mereka minati. Dengan mengetahui minat mereka, koneksi yang terjalin akan berada di tingkat yang berbeda. Jika brand yang berupaya dalam mengubah tujuan target pasar menjadi konsumen yang loyal atau berencana untuk merilis produk atau layanan terbaru ke pasar asing, minat pasar dan demografis menjadi penting dari informasi yang diperlukan.",
    galleryText: "",
    hiring: "https://www.sonarplatform.com/careers",
    socialMedia: {
      email: "info@sonar.id",
      linkedin: "https://www.linkedin.com/company/sonar-platform/",
      instagram: "https://www.instagram.com/sonarplatform/",
    },
    videoUrl: "https://youtube.com/embed/AK6LPCCQwpo",
    gallery: [
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sonar-a813e612-4439-4b61-bea0-f17b3a9e98fa.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sonar-abf8de1a-0660-46bc-b173-f37a556b8f09.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sonar-8bbdc6c0-1063-461d-ba68-66343a4adda7.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sonar-857af2b4-3488-4f24-9d86-1c361f006e6a.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sonar-e41b20b2-bca4-451c-9886-b001063a3c36.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sonar-caf6e5ac-e012-48be-a5f7-11185c982a2c.jpg",
      "https://arkavidia.nyc3.cdn.digitaloceanspaces.com/arkavidia/production/realitfestyep/sonar-dfb5f1d6-d564-4a8f-8d3f-e9fa56fd7271.jpg",
    ],
    contactLink: "https://wa.me/08118751495",
  },
};

export default Tenants;
